=== joseflaviojr/livre/Java/projeto/XML/Consulta.xsd
<?xml version="1.0" encoding="UTF-8"?>

<schema targetNamespace="http://www.joseflavio.com/xml"
	xmlns="http://www.w3.org/2001/XMLSchema"
	xmlns:tipo="http://www.joseflavio.com/xml"
	xmlns:consulta="http://www.joseflavio.com/xml"
	elementFormDefault="qualified"
	version="1.0">
<!-- ******************************************************************* -->
	<annotation>
		<documentation>
Copyright (C) 2014 José Flávio de Souza Dias Júnior

This file is part of José Flávio Livre - http://www.joseflavio.com/livre/.

José Flávio Livre is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

José Flávio Livre is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with José Flávio Livre. If not, see http://www.gnu.org/licenses/.
		</documentation>
	</annotation>
<!-- ******************************************************************* -->
	<annotation>
		<documentation>
Direitos Autorais Reservados (C) 2014 José Flávio de Souza Dias Júnior

Este arquivo é parte de José Flávio Livre - http://www.joseflavio.com/livre/.

José Flávio Livre é software livre: você pode redistribuí-lo e/ou modificá-lo
sob os termos da Licença Pública Menos Geral GNU conforme publicada pela
Free Software Foundation, tanto a versão 3 da Licença, como
(a seu critério) qualquer versão posterior.

José Flávio Livre é distribuído na expectativa de que seja útil,
porém, SEM NENHUMA GARANTIA; nem mesmo a garantia implícita de
COMERCIABILIDADE ou ADEQUAÇÃO A UMA FINALIDADE ESPECÍFICA. Consulte a
Licença Pública Menos Geral do GNU para mais detalhes.

Você deve ter recebido uma cópia da Licença Pública Menos Geral do GNU
junto com José Flávio Livre. Se não, veja http://www.gnu.org/licenses/.
		</documentation>
	</annotation>
<!-- ******************************************************************* -->
	<annotation>
		<documentation>
			http://www.joseflavio.com/xml/ConsultaExemplo.xml
		</documentation>
	</annotation>
<!-- ******************************************************************* -->
	<include schemaLocation="http://www.joseflavio.com/xml/Tipo.xsd"/>
<!-- ******************************************************************* -->
	<element name="consultas">
		<complexType>
			<sequence>

				<element name="parametro" minOccurs="0" maxOccurs="unbounded">
					<complexType>
						<complexContent>
							<extension base="consulta:Parametro"/>
						</complexContent>
					</complexType>
				</element>

				<element name="consulta" type="consulta:Consulta" minOccurs="1" maxOccurs="unbounded"/>
				
				<element name="traducao" type="consulta:Traducao" minOccurs="0" maxOccurs="unbounded"/>
				
				<element name="desconsiderar" minOccurs="0" maxOccurs="1">
					<complexType>
						<sequence>
							<element name="consulta" type="tipo:Texto" minOccurs="0" maxOccurs="unbounded"/>
						</sequence>
					</complexType>
				</element>

				<element name="documentacao" type="tipo:TextoMultilinha" minOccurs="0" maxOccurs="1"/>

			</sequence>
			<attribute name="descricao" type="tipo:Texto"/>
		</complexType>
		
		<key name="CP_Consultas_Consulta_Nome">
			<selector xpath="consulta:consulta"/>
			<field xpath="@nome"/>
		</key>
		<key name="CP_Consultas_Traducao_Nome">
			<selector xpath="consulta:traducao"/>
			<field xpath="@nome"/>
		</key>
		
		<keyref name="CE_Consultas_Consulta_Traducao_Tipo" refer="consulta:CP_Consultas_Traducao_Nome">
			<selector xpath="consulta:consulta/consulta:traducao"/>
			<field xpath="@tipo"/>
		</keyref>
		<keyref name="CE_Consultas_Desconsiderar_Consulta" refer="consulta:CP_Consultas_Consulta_Nome">
			<selector xpath="consulta:desconsiderar/consulta:consulta"/>
			<field xpath="."/>
		</keyref>
		
	</element>
<!-- ******************************************************************* -->
	<complexType name="Consulta">
		<sequence>
		
			<element name="parametro" minOccurs="0" maxOccurs="unbounded">
				<complexType>
					<complexContent>
						<extension base="consulta:Parametro"/>
					</complexContent>
				</complexType>
			</element>

			<element name="questionamento" type="tipo:TextoMultilinha" minOccurs="1" maxOccurs="1"/>
			
			<element name="traducao" minOccurs="0" maxOccurs="unbounded">
				<complexType>
					<attribute name="campo" type="tipo:Texto" use="required"/>
					<attribute name="tipo" type="tipo:Texto" use="required"/>
				</complexType>
			</element>

			<element name="documentacao" type="tipo:TextoMultilinha" minOccurs="0" maxOccurs="1"/>

		</sequence>
		<attribute name="nome" type="tipo:Texto" use="required"/>
		<attribute name="descricao" type="tipo:Texto"/>
	</complexType>
<!-- ******************************************************************* -->
	<complexType name="Parametro">
		<attribute name="nome" type="tipo:Texto" use="required"/>
		<attribute name="valor" type="consulta:ValorLivre" use="required"/>
		<attribute name="tipo" type="tipo:Tipo"/>
		<attribute name="alteravel" type="tipo:Logico"/>
	</complexType>
<!-- ******************************************************************* -->
	<complexType name="Traducao">
		<sequence>
			<element name="valor" minOccurs="1" maxOccurs="unbounded">
				<complexType>
					<attribute name="original" type="consulta:ValorLivre" use="required"/>
					<attribute name="traducao" type="consulta:ValorLivre" use="required"/>
				</complexType>
			</element>
		</sequence>
		<attribute name="nome" type="tipo:Texto" use="required"/>
	</complexType>
<!-- ******************************************************************* -->
	<simpleType name="ValorLivre">
		<restriction base="string">
			<pattern value="[^\n\r]*"/>
		</restriction>
	</simpleType>
<!-- ******************************************************************* -->
</schema>

=== joseflaviojr/livre/Java/projeto/XML/ConsultaExemplo.xml
<?xml version="1.0" encoding="UTF-8"?>

<consultas
	descricao="Exemplos de consultas"
	xmlns="http://www.joseflavio.com/xml"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.joseflavio.com/xml http://www.joseflavio.com/xml/Consulta.xsd">

	<parametro nome="jdbc" valor="org.postgresql.Driver"/>
	<parametro nome="url" valor="jdbc:postgresql://localhost:5432/exemplo"/>
	<parametro nome="usuario" valor="exemplo"/>
	<parametro nome="senha" valor="123456"/>

	<consulta nome="Exemplo" descricao="Exemplo de consulta">

		<parametro nome="nome completo" valor="A%" tipo="Texto" alteravel="S"/>
		<parametro nome="data de registro" valor="01/01/2001"/>

		<questionamento>
			select * from Exemplo
			where nome like ::nome completo:: and apelido = ::usuario:: and registro &gt;= ::data de registro::
			order by nome asc
		</questionamento>

		<traducao campo="sexo" tipo="Genero"/>
		<traducao campo="excluido" tipo="Logica"/>

		<documentacao>
			Documentação específica do Exemplo.
		</documentacao>

	</consulta>

	<consulta nome="Exemplo2" descricao="Segundo exemplo de consulta">
		<questionamento>
			select * from Exemplo2
		</questionamento>
		<traducao campo="valido" tipo="Logica"/>
	</consulta>

	<traducao nome="Logica">
		<valor original="0" traducao="Não"/>
		<valor original="1" traducao="Sim"/>
	</traducao>

	<traducao nome="Genero">
		<valor original="M" traducao="Masculino"/>
		<valor original="F" traducao="Feminino"/>
	</traducao>

	<desconsiderar>
		<consulta>Exemplo2</consulta>
	</desconsiderar>

	<documentacao>
			Documentação geral.
	</documentacao>

</consultas>
